agent_id: pi5-upstream-01
server_address: http://testflinger.local
logging_level: INFO
polling_interval: 10
job_queues:
  - pi5-upstream-smoke-01
execution_basedir: /home/ubuntu/testflinger-smoke/pi5-upstream-01/run
results_basedir: /home/ubuntu/testflinger-smoke/pi5-upstream-01/results
logging_basedir: /home/ubuntu/testflinger-smoke/pi5-upstream-01/logs
provision_type: noprovision
setup_command: /bin/true
provision_command: /bin/true
test_command: /bin/sh -c 'echo upstream-smoke-agent-01; hostname; uname -m'
cleanup_command: /bin/true
